csv_file = "data/topway_dashboard_alarms.csv"
update_interval = "5s"

[server]
listen_address = ":1502"

# ---------------------------------------------------------------------------
# Pre-degreasing tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 0
csv_column = "pre_degreasing_free_alkali_pv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 1
csv_column = "pre_degreasing_free_alkali_cv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 2
csv_column = "pre_degreasing_free_alkali_la_g_l"
scale = 100

[[registers]]
type = "holding"
address = 3
csv_column = "pre_degreasing_free_alkali_ha_g_l"
scale = 100

[[registers]]
type = "holding"
address = 4
csv_column = "pre_degreasing_total_alkali_pv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 5
csv_column = "pre_degreasing_total_alkali_cv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 6
csv_column = "pre_degreasing_total_alkali_la_g_l"
scale = 100

[[registers]]
type = "holding"
address = 7
csv_column = "pre_degreasing_total_alkali_ha_g_l"
scale = 100

[[registers]]
type = "holding"
address = 8
csv_column = "pre_degreasing_temperature_pv_c"
scale = 10

[[registers]]
type = "coil"
address = 0
csv_column = "pre_degreasing_free_alkali_low_alarm_active"

[[registers]]
type = "coil"
address = 1
csv_column = "pre_degreasing_free_alkali_high_alarm_active"

[[registers]]
type = "coil"
address = 2
csv_column = "pre_degreasing_total_alkali_low_alarm_active"

[[registers]]
type = "coil"
address = 3
csv_column = "pre_degreasing_total_alkali_high_alarm_active"

# ---------------------------------------------------------------------------
# Degreasing tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 9
csv_column = "degreasing_free_alkali_pv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 10
csv_column = "degreasing_free_alkali_cv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 11
csv_column = "degreasing_free_alkali_la_g_l"
scale = 100

[[registers]]
type = "holding"
address = 12
csv_column = "degreasing_free_alkali_ha_g_l"
scale = 100

[[registers]]
type = "holding"
address = 13
csv_column = "degreasing_total_alkali_pv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 14
csv_column = "degreasing_total_alkali_cv_g_l"
scale = 100

[[registers]]
type = "holding"
address = 15
csv_column = "degreasing_total_alkali_la_g_l"
scale = 100

[[registers]]
type = "holding"
address = 16
csv_column = "degreasing_total_alkali_ha_g_l"
scale = 100

[[registers]]
type = "holding"
address = 17
csv_column = "degreasing_temperature_pv_c"
scale = 10

[[registers]]
type = "coil"
address = 4
csv_column = "degreasing_free_alkali_low_alarm_active"

[[registers]]
type = "coil"
address = 5
csv_column = "degreasing_free_alkali_high_alarm_active"

[[registers]]
type = "coil"
address = 6
csv_column = "degreasing_total_alkali_low_alarm_active"

[[registers]]
type = "coil"
address = 7
csv_column = "degreasing_total_alkali_high_alarm_active"

# ---------------------------------------------------------------------------
# Silane tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 18
csv_column = "silane_ph_pv"
scale = 100

[[registers]]
type = "holding"
address = 19
csv_column = "silane_ph_cv"
scale = 100

[[registers]]
type = "holding"
address = 20
csv_column = "silane_ph_la"
scale = 100

[[registers]]
type = "holding"
address = 21
csv_column = "silane_ph_ha"
scale = 100

[[registers]]
type = "holding"
address = 22
csv_column = "silane_zirconium_pv_mg_l"
scale = 100

[[registers]]
type = "holding"
address = 23
csv_column = "silane_zirconium_cv_mg_l"
scale = 100

[[registers]]
type = "holding"
address = 24
csv_column = "silane_zirconium_la_mg_l"
scale = 100

[[registers]]
type = "holding"
address = 25
csv_column = "silane_zirconium_ha_mg_l"
scale = 100

[[registers]]
type = "holding"
address = 26
csv_column = "silane_ec_pv_us_cm"
scale = 100

[[registers]]
type = "holding"
address = 27
csv_column = "silane_ec_cv_us_cm"
scale = 100

[[registers]]
type = "holding"
address = 28
csv_column = "silane_ec_la_us_cm"
scale = 100

[[registers]]
type = "holding"
address = 29
csv_column = "silane_ec_ha_us_cm"
scale = 100

[[registers]]
type = "coil"
address = 8
csv_column = "silane_ph_low_alarm_active"

[[registers]]
type = "coil"
address = 9
csv_column = "silane_ph_high_alarm_active"

[[registers]]
type = "coil"
address = 10
csv_column = "silane_zirconium_low_alarm_active"

[[registers]]
type = "coil"
address = 11
csv_column = "silane_zirconium_high_alarm_active"

[[registers]]
type = "coil"
address = 12
csv_column = "silane_ec_low_alarm_active"

[[registers]]
type = "coil"
address = 13
csv_column = "silane_ec_high_alarm_active"

# ---------------------------------------------------------------------------
# Water rinse tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 30
csv_column = "water_rinse_ec_pv_us_cm"

[[registers]]
type = "holding"
address = 31
csv_column = "water_rinse_ec_cv_us_cm"

[[registers]]
type = "holding"
address = 32
csv_column = "water_rinse_ec_la_us_cm"

[[registers]]
type = "holding"
address = 33
csv_column = "water_rinse_ec_ha_us_cm"

[[registers]]
type = "holding"
address = 34
csv_column = "water_rinse_ph_pv"
scale = 100

[[registers]]
type = "holding"
address = 35
csv_column = "water_rinse_ph_cv"
scale = 100

[[registers]]
type = "holding"
address = 36
csv_column = "water_rinse_ph_la"
scale = 100

[[registers]]
type = "holding"
address = 37
csv_column = "water_rinse_ph_ha"
scale = 100

[[registers]]
type = "coil"
address = 14
csv_column = "water_rinse_ec_low_alarm_active"

[[registers]]
type = "coil"
address = 15
csv_column = "water_rinse_ec_high_alarm_active"

[[registers]]
type = "coil"
address = 16
csv_column = "water_rinse_ph_low_alarm_active"

[[registers]]
type = "coil"
address = 17
csv_column = "water_rinse_ph_high_alarm_active"

# ---------------------------------------------------------------------------
# Pre-coat DI rinse tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 38
csv_column = "precoat_di_rinse_ec_pv_us_cm"

[[registers]]
type = "holding"
address = 39
csv_column = "precoat_di_rinse_ec_cv_us_cm"

[[registers]]
type = "holding"
address = 40
csv_column = "precoat_di_rinse_ec_la_us_cm"

[[registers]]
type = "holding"
address = 41
csv_column = "precoat_di_rinse_ec_ha_us_cm"

[[registers]]
type = "holding"
address = 42
csv_column = "precoat_di_rinse_ph_pv"
scale = 100

[[registers]]
type = "holding"
address = 43
csv_column = "precoat_di_rinse_ph_cv"
scale = 100

[[registers]]
type = "holding"
address = 44
csv_column = "precoat_di_rinse_ph_la"
scale = 100

[[registers]]
type = "holding"
address = 45
csv_column = "precoat_di_rinse_ph_ha"
scale = 100

[[registers]]
type = "coil"
address = 18
csv_column = "precoat_di_rinse_ec_low_alarm_active"

[[registers]]
type = "coil"
address = 19
csv_column = "precoat_di_rinse_ec_high_alarm_active"

[[registers]]
type = "coil"
address = 20
csv_column = "precoat_di_rinse_ph_low_alarm_active"

[[registers]]
type = "coil"
address = 21
csv_column = "precoat_di_rinse_ph_high_alarm_active"

# ---------------------------------------------------------------------------
# E-coat tank
# ---------------------------------------------------------------------------
[[registers]]
type = "holding"
address = 46
csv_column = "ecoat_tank_ec_pv_us_cm"

[[registers]]
type = "holding"
address = 47
csv_column = "ecoat_tank_ec_cv_us_cm"

[[registers]]
type = "holding"
address = 48
csv_column = "ecoat_tank_ec_la_us_cm"

[[registers]]
type = "holding"
address = 49
csv_column = "ecoat_tank_ec_ha_us_cm"

[[registers]]
type = "holding"
address = 50
csv_column = "ecoat_tank_ph_pv"
scale = 100

[[registers]]
type = "holding"
address = 51
csv_column = "ecoat_tank_ph_cv"
scale = 100

[[registers]]
type = "holding"
address = 52
csv_column = "ecoat_tank_ph_la"
scale = 100

[[registers]]
type = "holding"
address = 53
csv_column = "ecoat_tank_ph_ha"
scale = 100

[[registers]]
type = "coil"
address = 22
csv_column = "ecoat_tank_ec_low_alarm_active"

[[registers]]
type = "coil"
address = 23
csv_column = "ecoat_tank_ec_high_alarm_active"

[[registers]]
type = "coil"
address = 24
csv_column = "ecoat_tank_ph_low_alarm_active"

[[registers]]
type = "coil"
address = 25
csv_column = "ecoat_tank_ph_high_alarm_active"
